# DC schema

# --- !Ups

CREATE TABLE ITEM (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRICE_VALUE INT NOT NULL,
    PRICE_CURRENCY VARCHAR(255) NOT NULL,
    COLOUR VARCHAR(255) NOT NULL,
    TAGS VARCHAR(255) NOT NULL,
    SIZE_VALUE INT NOT NULL,
    SIZE_REGION VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    SKU VARCHAR(255) NOT NULL
);

CREATE TABLE STOCK (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUANTITIES_COUNT INT NOT NULL,
    QUANTITIES_STATE VARCHAR(255) NOT NULL,
    SKU VARCHAR(255) NOT NULL,
    STOCK_ITEM_ID INT NOT NULL,
    FOREIGN KEY (STOCK_ITEM_ID) REFERENCES ITEM(ID),
    STOCK_STATE VARCHAR(255) NOT NULL
);

# --- !Downs

DROP TABLE ITEM;
DROP TABLE STOCK;
